### ISSUE TITLE
RI-01: usuarios

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#1]
# descripcion
**como**: administrador

**quiero**: poder consultar los siguientes datos de los usuarios:
- Nombre
- Apellidos
- Fecha de nacimiento
- Nombre
- Usuario 
- correo electrónico

# to-do
- [x] configuración en wordpress

# aceptacion
- [x] usuarios contienen los datos solicitados

**Comment by JSnow11** [comment]
# petición de cambio
- fecha de nacimiento no es añadible como campo al registro de woo-commerce
- se solicita eliminarla del requisito

**Comment by JSnow11** [comment]
# implementado

modificable tal como está indicado en la tarea #15 mediante el enlace http://20.107.0.136/wordpress/index.php/mi-cuenta/edit-account/

![image](https://user-images.githubusercontent.com/47798577/143091213-95eaece0-d9ab-42bb-8d53-11d25182a640.png)

**Comment by ferrabled** [comment]
Todo correcto, funciona y muestra los datos correctamente
