### ISSUE TITLE
RF-03: Ver patinetes en el Mapa

### ISSUE THREAD

**Issue by ferrabled** [IS-PGPI-G11/patinetsi#11]
# descripción
*como*: administrador 

*quiero*: quiero poder ver la lista de los patines del sistema en un mapa.

# to-do
- [x] Mostar en un listado de todos los patinetes

# aceptación
- [x] El listado de patinetes se muestra correctamente en la pagina principal

**Comment by josaloroc** [comment]
Muy similar a #3. ¿Consideramos cerrarla al finalizar dicha tarea?

**Comment by JSnow11** [comment]
## review
- funciona correctamente
- enlaces desde el mapa a los productos correctos
- zonas también visibles
