### ISSUE TITLE
RF-09: Zonas patinete

### ISSUE THREAD

**Issue by pedalopon** [IS-PGPI-G11/patinetsi#12]
# descripción
*como*:  usuario 

*quiero*: consultar las zonas habilitadas donde poder dejar el patinete

# to-do
- [x] Añadir nuevos marcadores de zonas al mapa.

# aceptación
- [x] Se muestran las diferentes zonas donde se puede dejar el patinete.

No olviden estimar temporalmente esta historia y planificarla dentro de la línea de producción del sprint en el que vaya a ser desarrollada.

**Comment by josaloroc** [comment]
Se han añadido nuevos marcadores (iconos rojos) que indican las posibles zonas de desbloqueo de patinetes.
![Captura](https://user-images.githubusercontent.com/64849766/144843955-04c21103-f31c-4b23-b19a-5c03f4d4fc8c.PNG)

**Comment by JSnow11** [comment]
## review
- las zonas de desbloqueo aparecen en el mapa
