### ISSUE TITLE
RNF-03: Tiempo de respuesta

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#14]
# descripción
*como*: administrador
*quiero*: que la aplicación tenga un tiempo de respuesta óptimo
*para*: fomentar una buena experiencia del usuario en la aplicación.

# to-do
- [x] Desplegar la aplicación en Azure para que nos ofrezca un tiempo de respuesta optimo

# aceptación
- [ ] Comprobar que hay un buen tiempo de respuesta

**Comment by JSnow11** [comment]
## review
- correcto
