### ISSUE TITLE
RF-04: Dar de alta usuario

### ISSUE THREAD

**Issue by ferrabled** [IS-PGPI-G11/patinetsi#15]
# descripción
*como*: usuario

*quiero*: poder darme de alta en el sistema.

# to-do
- [x] configuración wordpress

# aceptación
- [x] se pueden registrar clientes y usuarios

**Comment by JSnow11** [comment]
# implementado
configurada la opción de registro

## test
- registro en http://20.107.0.136/wordpress/index.php/mi-cuenta/
- editar la cuenta en http://20.107.0.136/wordpress/index.php/mi-cuenta/edit-account/

**Comment by ferrabled** [comment]
Registro y edición de usuarios funcionando correctamente
