### ISSUE TITLE
RF-12: generar QR asociado

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#16]
# descripción
*como*: administrador

*quiero*: poder generar un código QR y asignarlo a un patín.

# to-do
- [x] encontrar plugin
- [x] configurar plugin

# aceptación
- [x] se pueden generar QRs asociados a los patines

**Comment by JSnow11** [comment]
## implementado
- comprobar en la url: http://20.107.0.136/wordpress/wp-admin/admin.php?page=woo_bulk_qr_codes

**Comment by josaloroc** [comment]
# review
- Comprobado el funcionamiento de la generación de QR sobre patines.

## sugerencia
- Nada por comentar al respecto.
