### ISSUE TITLE
RF-01: Visualizar Usuarios Registrados

### ISSUE THREAD

**Issue by ferrabled** [IS-PGPI-G11/patinetsi#2]
# descripción
**como:** administrador

**quiero:** poder ver la lista de los usuarios registrados.

# to-do
- [x] Instalar plugins necesarios para mostrar una lista de usuarios

# aceptación
- [x] Se muestra una lista de usuarios en la vista de administración

**Comment by pedalopon** [comment]
El listado de usuarios se encontrara en este  [link](http://20.107.0.136/wordpress/wp-admin/users.php)

**Comment by JSnow11** [comment]
# review
- el link facilitado lleva a la vista de todos los usuarios
- los clientes en concreto pueden verse mediante el link: http://20.107.0.136/wordpress/wp-admin/users.php?role=customer
