### ISSUE TITLE
RN-01: Limitación de zonas

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#21]
# descripción
*como*: administrador
*quiero*: que el usuario solo pueda acceder y/o dejar en las zonas habilitadas
*para*: establecer los límites de uso del servicio.

# to-do
- [x] Añadir limitación de activación a España

# aceptación
- [x]  Al realizar una compra, se muestra el "envío" limitado a España de forma que se limita la activación de patines a este país. No obstante, se puede elegir la provincia para enviar.

**Comment by JSnow11** [comment]
## to-do
- petición de cambio, fuera de alcance técnico

**Comment by josaloroc** [comment]
Similar a #22 , se cerrará al completar dicha tarea.

**Comment by JSnow11** [comment]
## review
- se cumple con la restricción de país
- la petición de cambio fue aceptada
