### ISSUE TITLE
RN-02: Zona de uso

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#22]
# descripción
*como*: administrador
*quiero*: que las zonas habilitadas sean exclusivamente en Sevilla
*para*: establecer los límites de uso.

# to-do
- [x] Añadir limitación de activación a España

# aceptación
- [x] Al realizar una compra, se muestra el "envío" limitado a España de forma que se limita la activación de patines a este país. No obstante, se puede elegir la provincia para enviar.

No olviden estimar temporalmente esta historia y planificarla dentro de la línea de producción del sprint en el que vaya a ser desarrollada.

**Comment by josaloroc** [comment]
Petición del cambio: tras investigar, no es posible limitar el desbloqueo de patines exclusivamente a Sevilla debido a las funcionalidades que ofrece por defecto WooCommerce. Sin embargo, si que es posible limitarlo solo a España.

**Comment by josaloroc** [comment]
Zona limitada a España. A la hora de seleccionar el país de "envío" al realizar una operación de compra, solo se puede marcar dicho país.
![image](https://user-images.githubusercontent.com/64849766/145682398-a2507ea8-974c-43be-9bf4-4db78cda3dae.png)
No obstante, también se puede seleccionar provincia.
![image](https://user-images.githubusercontent.com/64849766/145682425-87190fef-97a3-4e2a-8551-c4040c317649.png)

**Comment by JSnow11** [comment]
## review
- la limitación de país es efectiva
