### ISSUE TITLE
RN-03: Código QR

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#23]
# descripción
*como*: administrador
*quiero*: que los clientes deban escanear el código QR de los patines
*para*:  poder utilizar el patín

# to-do
- [x] petición de cambio
- [x] configuración

# aceptación
- [x] todo patín tiene un QR asociado

**Comment by JSnow11** [comment]
## to-do
- petición de cambio, no puede ser una regla, el QR es una opción para llegar a la vista de compra

**Comment by JSnow11** [comment]
> ## to-do
> * petición de cambio, no puede ser una regla, el QR es una opción para llegar a la vista de compra

ante la falta de respuesta se da por aceptada, todos los patines tienen un QR asociado, consultable en: http://20.107.0.136/wordpress/wp-admin/admin.php?page=woo_bulk_qr_codes
