### ISSUE TITLE
RN-07: horario de uso

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#24]
# descripción
*como*: administrador

*quiero*: que el horario de actividad (uso) de los patines sea de 7:00h a 00:00h.

# to-do
- [x] Implementar widget para mostrar el horario de uso de los patines.

# aceptación
- [ ] Se muestra correctamente el horario en la página

**Comment by josaloroc** [comment]
Se ha instalado un plugin para poder realizar una "Tarjeta Comercial" y mostrar el horario en uno de los laterales de la página.
![Captura](https://user-images.githubusercontent.com/64849766/144830867-18450a25-45cc-42a2-868f-7acb131192d8.PNG)

**Comment by JSnow11** [comment]
## review
- el horario aparece correctamente donde es relevante
