### ISSUE TITLE
RN-04: Coste de desbloqueo

### ISSUE THREAD

**Issue by josaloroc** [IS-PGPI-G11/patinetsi#25]
# descripción
*como*: administrador
*quiero*: que el coste de desbloquear el patín sea de 1€ y a partir de ahí de 0.15€/min
*para*: obtener beneficios del negocio

 **sugerencia**: usar el precio de envío como precio de desbloqueo

# to-do
- [x] configurar el precio adicional de envío o precio fijo

# aceptación
- [x] toda compra de minutos implica un coste de 1€ por desbloqueo

**Comment by JSnow11** [comment]
## related
#18

**Comment by JSnow11** [comment]
## implementado
- coste de activación añadido como envío:
![image](https://user-images.githubusercontent.com/47798577/144492661-cd311ba0-8060-4018-ae36-19ab126aadd5.png)

- puede probarse mediante una compra de minutos de cualquier patín

**Comment by josaloroc** [comment]
# review
- Comprobado que se añade el coste de activación al realizar la compra.

## sugerencia
- Nada por comentar al respecto.
