### ISSUE TITLE
RF-06: listado de patinetes

### ISSUE THREAD

**Issue by pedalopon** [IS-PGPI-G11/patinetsi#3]
# descripcion
como: usuario  
quiero: poder ver la lista de patines del sistema en un mapa

# to-do
- [x] Mostar en un listado de todos los patinetes

# aceptacion
- [x] El listado de patinetes se muestra correctamente en la pagina principal

No olviden estimar temporalmente esta historia y planificarla dentro de la linea de producción del sprint en el que vaya a ser desarrollada.

**Comment by pedalopon** [comment]
**Petición de cambio**

- No se puede mostrar las localizaciones de los patinetes en el mapa y guardar las localizaciones de las mismas.
- Se solicita cambiar/eliminar el requisito

**Comment by JSnow11** [comment]
## review
- funciona correctamente tras la petición de cambio
- catalogo de patinetes en tienda: http://20.107.0.136/wordpress/index.php/tienda/

**Comment by josaloroc** [comment]
Se muestra cada patinete correctamente desde el mapa
![image](https://user-images.githubusercontent.com/64849766/144866770-91299c05-04f2-436f-85c0-77503453ab50.png)

**Comment by ferrabled** [comment]
Se ha añadido una leyenda para entender mejor los marcadores del mapa
![image](https://user-images.githubusercontent.com/48551658/145030434-22e64346-8996-47a7-872b-783926f8a836.png)
