### ISSUE TITLE
Doc: Despliegue

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#40]
# Despliegue
**Nota**: puede consultarse esta misma documentación en el issue correspondiente: #40
### azure
Se ha hecho uso de la subscripción de estudiante gratuita de Azure ofrecida por la US.

El sitio wordpress ha sido instalado, desplegado y configurado manualmente en una máquina virtual.
Dicho proceso incluye:
- Contratación de la máquina virtual mediante el crédito de estudiante disponible.
- Acceso a dicha máquina virtual mediante ssh.
- Instalación de dependencias de wordpress.
- Instalación de wordpress.
- Instalación de apache y uso del puerto 80 para ofrecer el sitio wordpress en internet: http://20.107.0.136/wordpress
- Configuración de la dirección ip pública de la máquina virtual para mantenerla estable: [20.107.0.136](http://20.107.0.136/)
- Configuración de wordpress e instalación de plugins.

## acceso
Puesto que se hace uso de recursos personales, especialmente la cuenta virtual de la US, el acceso a la gestión de la máquina virtual queda restringido, administrado y gestionado por @JSnow11 (esoj.nieves@gmail.com o josmonnie1@alum.us.es).

Puede gestionarse el recurso desde azure: https://portal.azure.com/

Puede accederse a la máquina virtual mediante ssh: `ssh -i ./wp_key.pem azure-admin@20.107.0.136` (se requiere la clave, debe solicitarse al administrador)

## disponibilidad
La disponibilidad es configurable en el panel de gestión de azure.

Para que la aplicación pueda ser correctamente testeada esta estará disponible de 08:00 a 00:00 desde el día 15/12/2021 hasta que se indique que no es necesario que el sistema permanezca desplegado.

**Comment by ferrabled** [comment]
Revisado, todo correcto ✔️
