### ISSUE TITLE
Doc: Manual de uso

### ISSUE THREAD

**Issue by JSnow11** [IS-PGPI-G11/patinetsi#41]
# Manual de uso
**Nota**: puede consultarse esta misma documentación en el issue correspondiente: #41

## índice
  - [índice](#índice)
  - [administración](#administración)
    - [gestión](#gestión)
      - [introducir patines](#introducir-patines)
      - [actualizar patines](#actualizar-patines)
      - [códigos QR](#códigos-qr)
      - [pagos](#pagos)
      - [cupones](#cupones)
      - [incidencias](#incidencias)
    - [analisis](#analisis)
      - [funcionalidad solicitada](#funcionalidad-solicitada)
      - [lighthouse](#lighthouse)
  - [clientes](#clientes)
    - [catálogo](#catálogo)
    - [alquilar](#alquilar)
      - [aplicar un cupón](#aplicar-un-cupón)
    - [cuenta](#cuenta)
    - [notificar incidencias](#notificar-incidencias)

### gestión

Todas las funcionalidades de administración y gestión del negocio pueden ser realizadas por cualquier usuario administrador facilitado.

El equipo de dirección tiene un usuario asignado: **wp-director**
Deben hacer login con los credenciales facilitados por el equipo de desarrollo.

#### introducir patines

Los productos pueden listarse en el [apartado de productos](http://20.107.0.136/wordpress/wp-admin/edit.php?post_type=product)

Un nuevo patinete puede ser añadido en el [apartado nuevo producto](http://20.107.0.136/wordpress/wp-admin/post-new.php?post_type=product), para ello se introducirá:

- **título**, se recomienda seguir la estructura "Patinete-{Id}"
  ![image](https://user-images.githubusercontent.com/47798577/145689345-38024cc3-693a-46a2-88b9-d6d58f2ba97f.png)
- **párrafo**, donde se añadirá la pagina de detalles del producto al gusto, se recomienda añadir la localización actual mediante un iframe de google maps:
  ![image](https://user-images.githubusercontent.com/47798577/145033064-8a760b83-1f0c-4c48-a9b7-43eb90dfa903.png)
- **datos**, donde se recomienda indicar, al menos, **precio normal** (precio por minuto) y nota de precio para indicar que es por minuto:
  ![image](https://user-images.githubusercontent.com/47798577/145033481-e33751e9-7c37-4a50-a71c-6bf09eb0ea70.png)
- **atributos**, donde se pueden rellenar los atributos preconfigurados:
  ![image](https://user-images.githubusercontent.com/47798577/145033652-9fd94262-89b2-4325-9d64-a57e5f8ba972.png)

#### actualizar patines

Para acceder a la edición de un patín vaya al [apartado de productos](http://20.107.0.136/wordpress/wp-admin/edit.php?post_type=product) y seleccione o búsque el que desea editar. Una vez seleccionado puede tomarse como referencia la creación de patines antes citada como base para su edición.

Los patines con cierta ubicación deben ser añadidos al mapa de la pantalla inicial, puede realizarse en el apartado de [easy maps](http://20.107.0.136/wordpress/wp-admin/admin.php?page=google-maps-easy).

#### códigos QR

Se generan automáticamente para cada patín, pueden consultarse en la [sección de QR](http://20.107.0.136/wordpress/wp-admin/admin.php?page=woo_bulk_qr_codes) y pueden ser personalizados en la [sección de configuración QR](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wooqr).

#### pagos

Actualmente se ofrece pago por transferencia, la cuenta bancaria de destino debe ser confirmada por el dueño del negocio.

El resto de métodos de pago deben ser configurados con los datos de facturación oportunos en la sección de [pagos](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Fconnect):
![image](https://user-images.githubusercontent.com/47798577/145689387-33535627-7783-4227-af1a-3ed8a917a4c1.png)

#### cupones

Los cupones pueden ser gestionados en la [sección de cupones](http://20.107.0.136/wordpress/wp-admin/edit.php?post_type=shop_coupon).

- Existe un cupón predefinido para viajes de más de 2 horas en un patín. `2hours`.
- Existe un cupón de prueba de activación gratuita: `ActivaGratis`.

![image](https://user-images.githubusercontent.com/47798577/145689418-f6fd2def-cd59-4080-a7b0-5b7270134a08.png)

Los usuarios pueden usar cupones de activación para poder hacer uso de "envío" (activación) gratuita cuando dispongan de dichos cupones. (Véase también, [envios](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=1)).

Estos cupones deben ser gestionados y configurados previamente y no pueden ser aplicados de forma automática.

#### incidencias

Cuando los clientes notifican incidencias el administrador puede consultarlas en el panel de control en la [sección de incidencias](http://20.107.0.136/wordpress/wp-admin/admin.php?page=cfdb7-list.php&fid=60):
![image](https://user-images.githubusercontent.com/47798577/145689296-fb51f6d6-2f68-4f7d-95c6-08cff5f7bcd6.png)

### analisis

La información de análisis es consultable en el [modulo de analitica](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Foverview) de woo commerce.

Más información es accesible mediante la barra de menú:
![image](https://user-images.githubusercontent.com/47798577/145027998-878626be-e985-4a88-8271-d9ae494258fc.png)

#### funcionalidad solicitada

- el nº de alquileres es consultable en la overview, viendo **pedidos**
  ![image](https://user-images.githubusercontent.com/47798577/145028093-02e93d94-e1b5-4fe5-a2b1-4762a58ab8c0.png) o también en el apartado de [pedidos](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Forders).

- el tiempo de uso y dinero ingresado en general también es consultable como **articulos** (minutos) y **ventas netas** (coste de uso, no incluye activación), observable en la imagen anterior o también en el apartado concreto de [ingresos](http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue).

- pueden realizarse consultas por patín en concreto, clicando en el patin dentro del modulo de analisis o mediante la url correspondiente, pe: <http://20.107.0.136/wordpress/wp-admin/admin.php?page=wc-admin&filter=single_product&products=14&path=%2Fanalytics%2Fproducts> :
  ![image](https://user-images.githubusercontent.com/47798577/145689540-4f0edd49-1761-4297-a718-4ca67d956269.png)

- los clientes pueden listarse en el apartado de [clientes](http://20.107.0.136/wordpress/wp-admin/users.php?role=customer):
  ![image](https://user-images.githubusercontent.com/47798577/144494148-26f8820a-bc7d-4f0c-aa77-652c8d865be6.png)

#### lighthouse

Se recomienda el uso de lighthouse para el análisis de diferentes métricas del sitio web.
Los resultados actuales tras el desarrollo son:
![image](https://user-images.githubusercontent.com/47798577/145674691-19e193ae-6aa5-4aad-8b5d-6ac10082cc05.png)

### catálogo

Los patines pueden ser geolocalizados en la [ventana principal](http://20.107.0.136/wordpress/) mediante el mapa:
![image](https://user-images.githubusercontent.com/47798577/145689078-11773fbb-9067-4373-8f75-7f3de2a4660c.png)
Si se hace click en alguno de los indicadores del mapa se redireccionará a la página de detalle del patín.

También pueden ser listados en la [tienda](http://20.107.0.136/wordpress/index.php/tienda/):
![image](https://user-images.githubusercontent.com/47798577/145689096-47137c18-b258-404f-bab5-be4aede3654b.png) o buscados mediante la barra de búsqueda.

Por último pueden ser accedidos mediante el QR asociado, que debe haber sido distribuido y pegado en el patín con anterioridad.

### alquilar

1. Selección de patín: puede accederse a un patín concreto mediante cualquiera de las formas citadas en el apartado de catálogo.

2. Tiempo de uso: una vez el usuario elige un patín debe indicar el nº de minutos de uso como cantidad y añadir al carrito:
   ![image](https://user-images.githubusercontent.com/47798577/145689109-2a5c577b-c1cd-46f5-9643-0b05a4deb7bb.png)

3. Pago: el usuario debe dirigirse al [carrito](http://20.107.0.136/wordpress/index.php/carrito/), comprobar los datos del pedido, indicar los datos de facturación, seleccionar el método de pago y realizar el pedido:
   ![image](https://user-images.githubusercontent.com/47798577/145689148-ce3f7758-752c-4860-8dc5-5901b50bd99e.png)
   ![image](https://user-images.githubusercontent.com/47798577/145689155-b835243e-b278-4e39-8c9e-2b2d1bd6ec91.png)
   ![image](https://user-images.githubusercontent.com/47798577/145689167-d4a52fe1-fd52-4ca8-bb2f-3302b8b0ded3.png)
   ![image](https://user-images.githubusercontent.com/47798577/145689179-5b6213e4-b6c6-491e-9ec0-764d11d05144.png)
   ![image](https://user-images.githubusercontent.com/47798577/145689180-f030d44d-e64d-490b-8e6f-40dfe8418e4e.png)

4. Confirmación y activación: En caso de transferencia bancaria, se indicará la cuenta y se deberá realizar la transferencia. Una vez recibido el pago el patinete se desbloqueará durante el tiempo de adquisición exacto.
   ![image](https://user-images.githubusercontent.com/47798577/145036043-41124900-feca-44e7-b7cb-3d0f578cf56f.png)

#### aplicar un cupón

Una vez el usuario elige un patín y los minutos de uso, en el carrito, puede aplicar un cupón:
![image](https://user-images.githubusercontent.com/47798577/145688697-2fc71d0e-8099-4ea6-9703-8abe5f6d33be.png)

Para poder usar el cupón el pedido y el usuario deben cumplir los requisitos establecidos en el cupón y dicho cupón debe estar activo y no haber caducado.

Otro ejemplo, activación gratuita:
![image](https://user-images.githubusercontent.com/47798577/145688822-1166ab51-1643-4f25-8f3a-32d622339580.png)

Resultado con ambos cupones aplicados:
![image](https://user-images.githubusercontent.com/47798577/145688841-4cf48c61-0cc9-45fa-ba12-621156298de0.png)

### cuenta

En la vista de [mi cuenta](http://20.107.0.136/wordpress/index.php/mi-cuenta/), el cliente puede consultar su cuenta, modificar sus datos, ver últimos viajes (pedidos) , gestionar y predefinir direcciones de facturación y envío y cambiar sus credenciales.

### notificar incidencias

Las incidencias pueden ser comunicadas en el apartado de [contáctanos](http://20.107.0.136/wordpress/index.php/contact/):
![image](https://user-images.githubusercontent.com/47798577/145689240-785ea53a-cd55-4b8a-aad3-4862f4e87ece.png)

**Comment by ferrabled** [comment]
Explicación concisa, facilitando mucho entender cómo usar la aplicación ✔️
